// @vitest-environment jsdom

import React from "react";
import { act } from "react";
import { createRoot, type Root } from "react-dom/client";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { PublicKey, SystemProgram, Transaction, TransactionInstruction } from "@solana/web3.js";
import { MIN_CLAIM_BALANCE, SOUL_PROVENANCE_SIDE, TARGET_AMM, claimSoul } from "sdk";
import { ClaimButton, getClaimDisabledReason } from "./ClaimButton";
import type { SoulAccount } from "sdk";

(globalThis as typeof globalThis & { IS_REACT_ACT_ENVIRONMENT: boolean }).IS_REACT_ACT_ENVIRONMENT = true;

const mocks = vi.hoisted(() => ({
  connection: { rpcEndpoint: "https://api.devnet.solana.com" },
  publicKey: { toBase58: () => "8uAPC2UxiBjKmUksVVwUA6q4RctiXkgSAsovBR39cd1i" },
  sendTransaction: vi.fn(async () => "ClaimSig1111111111111111111111111111111111111"),
}));

const connectedWallet = new PublicKey(mocks.publicKey.toBase58());

vi.mock("@solana/wallet-adapter-react", () => ({
  useConnection: () => ({ connection: mocks.connection }),
  useWallet: () => ({
    connected: true,
    publicKey: mocks.publicKey,
    sendTransaction: mocks.sendTransaction,
  }),
}));

vi.mock("next-intl", () => ({
  useTranslations: () => (key: string, values?: Record<string, string>) => {
    if (key === "claim") {
      return "Claim Soul";
    }
    if (key === "claimed") {
      return "Claimed";
    }
    if (key === "claiming") {
      return "Claiming…";
    }
    if (key === "success") {
      return `Claimed NFT ${values?.mint ?? ""}`;
    }
    if (key === "signature") {
      return `Signature: ${values?.signature ?? ""}`;
    }
    if (key === "viewInMySouls") {
      return "View in My Souls";
    }
    if (key === "errorFallback") {
      return "Claim failed";
    }
    if (key === "errors.walletRejected") {
      return "Claim was not signed. Approve the wallet request when you are ready.";
    }
    if (key === "disabled.provenanceSellGenerated") {
      return "The latest Soul was generated by a sell, so it is a visual market moment only—not a claimable MT/Soul NFT.";
    }
    if (key.startsWith("errors.")) {
      return "Claim did not complete. Nothing changed; retry when ready.";
    }
    const messages: Record<string, string> = {
      ariaLabel: "Pre-sign decoded transaction review",
      title: "Pre-sign decoded transaction review",
      summary: `Cluster: ${values?.cluster ?? ""}; blockhash: ${values?.blockhash ?? ""}; fee payer: ${values?.feePayer ?? ""}`,
      pending: "pending",
      programIds: `Program IDs: ${values?.programIds ?? ""}`,
      instructionTitle: `#${values?.index ?? ""} Program ${values?.programId ?? ""}`,
      accounts: `Accounts: ${values?.accounts ?? ""}`,
      receiptIntentTitle: "Receipt settlement intent",
      receiptIntentBody: `${values?.state ?? ""} ${values?.amount ?? ""} base units from ${values?.source ?? ""}.`,
      unknownSource: "unknown source",
      unknown: "unknown",
      receiptCapacity: `Active receipts: ${values?.activeReceiptCount ?? ""}; post-move whole-token capacity: ${values?.postWholeUnits ?? ""}.`,
      selectedReceipts: `Selected receipts: ${values?.receipts ?? ""}`,
      none: "none",
      "flags.signer": "signer",
      "flags.nonSigner": "non-signer",
      "flags.writable": "writable",
      "flags.readonly": "readonly",
    };
    if (messages[key]) {
      return messages[key];
    }
    return key;
  },
}));

vi.mock("./PauseBanner", () => ({
  usePauseStatus: () => ({ isPaused: false }),
}));

vi.mock("@/i18n/navigation", () => ({
  Link: ({
    children,
    href,
    ...props
  }: React.PropsWithChildren<{ href: string; className?: string }>) =>
    React.createElement("a", { href, ...props }, children),
}));

vi.mock("sdk", async (importOriginal) => {
  const actual = await importOriginal<typeof import("sdk")>();
  return {
    ...actual,
    claimSoul: vi.fn(async (params: {
      connection: unknown;
      payer: PublicKey;
      sendTransaction: (
        transaction: Transaction,
        connection: unknown,
      ) => Promise<string>;
    }) => {
      const feePayer = new PublicKey(params.payer.toBase58());
      const transaction = new Transaction({
        feePayer,
        recentBlockhash: "11111111111111111111111111111111",
      }).add(
        new TransactionInstruction({
          programId: SystemProgram.programId,
          keys: [{ pubkey: feePayer, isSigner: true, isWritable: true }],
          data: Buffer.alloc(0),
        }),
      );
      return params.sendTransaction(transaction, params.connection);
    }),
  };
});

const claimSoulMock = vi.mocked(claimSoul);

function soul(overrides: Partial<SoulAccount> = {}): SoulAccount {
  return {
    mint: PublicKey.unique(),
    authority: PublicKey.unique(),
    createdAt: 1n,
    generationCount: 1n,
    lastSvgLen: 11,
    lastSvg: "<svg></svg>",
    lastSvgBytes: new TextEncoder().encode("<svg></svg>"),
    templateLen: 0,
    baseSvgTemplate: "",
    baseSvgTemplateBytes: new Uint8Array(),
    styleParamsLen: 0,
    styleParams: "",
    styleParamsBytes: new Uint8Array(),
    minClaimBalance: 0n,
    claimCount: 0n,
    memeSymbol: "",
    memeSymbolBytes: new Uint8Array(),
    memeSymbolLen: 0,
    targetAmm: TARGET_AMM.Raydium,
    provenanceGeneration: 0n,
    provenanceSide: SOUL_PROVENANCE_SIDE.None,
    provenanceAmount: 0n,
    provenanceTokenAmount: 0n,
    provenanceTrader: PublicKey.default,
    provenanceTokenAccount: PublicKey.default,
    provenanceMint: PublicKey.default,
    provenanceSoul: PublicKey.default,
    provenanceSeedHash: new Uint8Array(8),
    provenanceSeedHashHex: "0000000000000000",
    ...overrides,
  };
}

function claimableSoul(overrides: Partial<SoulAccount> = {}): SoulAccount {
  const generationCount = overrides.generationCount ?? 1n;
  return soul({
    generationCount,
    claimCount: 0n,
    provenanceGeneration: generationCount,
    provenanceSide: SOUL_PROVENANCE_SIDE.Buy,
    provenanceAmount: 5_000_000_000n,
    provenanceTokenAmount: MIN_CLAIM_BALANCE,
    provenanceTrader: connectedWallet,
    ...overrides,
  });
}

describe("ClaimButton", () => {
  let container: HTMLDivElement;
  let root: Root;
  const originalSmokeFlag = process.env.NEXT_PUBLIC_DEVNET_SMOKE;
  const originalRpc = process.env.NEXT_PUBLIC_RPC;

  beforeEach(() => {
    process.env.NEXT_PUBLIC_DEVNET_SMOKE = undefined;
    process.env.NEXT_PUBLIC_RPC = "https://api.devnet.solana.com";
    claimSoulMock.mockClear();
    mocks.sendTransaction.mockClear();
    container = document.createElement("div");
    document.body.appendChild(container);
    root = createRoot(container);
  });

  afterEach(async () => {
    if (root) {
      await act(async () => {
        root.unmount();
      });
    }
    container.remove();
    process.env.NEXT_PUBLIC_DEVNET_SMOKE = originalSmokeFlag;
    process.env.NEXT_PUBLIC_RPC = originalRpc;
  });

  async function renderClaimButton(mint: PublicKey, nextSoul: SoulAccount) {
    await act(async () => {
      root.render(
        React.createElement(ClaimButton, {
          mint,
          soul: nextSoul,
          walletTokenBalanceBaseUnits: MIN_CLAIM_BALANCE,
          isTokenBalanceLoading: false,
        }),
      );
    });
  }

  function claimButton() {
    const button = container.querySelector<HTMLButtonElement>("button");
    if (!button) {
      throw new Error("Claim button was not rendered");
    }
    return button;
  }

  it("reenables after a local claim success when a later generation is unclaimed", async () => {
    const mint = PublicKey.unique();

    await renderClaimButton(mint, claimableSoul({ mint, generationCount: 1n, claimCount: 0n }));
    expect(claimButton().disabled).toBe(false);
    expect(claimButton().textContent).toBe("Claim Soul");

    await act(async () => {
      claimButton().click();
    });

    expect(claimSoulMock).toHaveBeenCalledOnce();
    expect(mocks.sendTransaction).toHaveBeenCalledOnce();
    expect(claimButton().disabled).toBe(false);
    expect(claimButton().textContent).toBe("Claim Soul");
    expect(container.textContent).toContain("Claimed NFT");
    const mySoulsLink = container.querySelector<HTMLAnchorElement>('a[href="/profile"]');
    expect(mySoulsLink?.textContent).toBe("View in My Souls");
    const review = container.querySelector<HTMLElement>(
      '[data-testid="claim-pre-sign-transaction-review"]',
    );
    expect(review?.textContent).toContain("Pre-sign decoded transaction review");
    expect(review?.textContent).toContain("Cluster: devnet");
    expect(review?.textContent).toContain("Program IDs:");

    await renderClaimButton(mint, claimableSoul({ mint, generationCount: 1n, claimCount: 1n }));
    expect(claimButton().disabled).toBe(true);
    expect(claimButton().textContent).toBe("Claimed");

    await renderClaimButton(mint, claimableSoul({ mint, generationCount: 2n, claimCount: 1n }));
    expect(claimButton().disabled).toBe(false);
    expect(claimButton().textContent).toBe("Claim Soul");
  });

  it("keeps claim wallet-signed even when the retired devnet smoke flag is present", async () => {
    process.env.NEXT_PUBLIC_DEVNET_SMOKE = "1";
    const fetchMock = vi.fn();
    vi.stubGlobal("fetch", fetchMock);
    const mint = PublicKey.unique();

    await renderClaimButton(mint, claimableSoul({ mint, generationCount: 1n, claimCount: 0n }));

    await act(async () => {
      claimButton().click();
    });

    expect(claimSoulMock).toHaveBeenCalledOnce();
    expect(claimSoulMock).toHaveBeenCalledWith(
      expect.objectContaining({
        sendTransaction: expect.any(Function),
      }),
    );
    expect(fetchMock).not.toHaveBeenCalledWith(
      "/api/devnet-smoke",
      expect.objectContaining({ method: "POST" }),
    );
    vi.unstubAllGlobals();
  });

  it("shows a localized rejected-wallet claim result without raw SDK text", async () => {
    const mint = PublicKey.unique();
    mocks.sendTransaction.mockRejectedValueOnce(
      new Error("User rejected the request: failed with custom program error: 0x1771"),
    );

    await renderClaimButton(mint, claimableSoul({ mint, generationCount: 1n, claimCount: 0n }));

    await act(async () => {
      claimButton().click();
    });

    expect(claimSoulMock).toHaveBeenCalledOnce();
    expect(container.textContent).toContain(
      "Claim was not signed. Approve the wallet request when you are ready.",
    );
    expect(container.textContent).not.toContain("custom program error");
    expect(container.textContent).not.toContain("0x1771");
  });

  it("explains that sell-generated Souls are visual moments rather than claimable MTs", async () => {
    const mint = PublicKey.unique();

    await renderClaimButton(
      mint,
      soul({
        mint,
        generationCount: 2n,
        claimCount: 1n,
        provenanceGeneration: 2n,
        provenanceSide: SOUL_PROVENANCE_SIDE.Sell,
        provenanceAmount: 10_000_000n,
        provenanceTokenAmount: 0n,
        provenanceTrader: connectedWallet,
      }),
    );

    expect(claimButton().disabled).toBe(true);
    expect(container.textContent).toContain("visual market moment only");
    expect(container.textContent).toContain("not a claimable MT/Soul NFT");
  });
});

describe("getClaimDisabledReason", () => {
  it("requires a connected wallet", () => {
    expect(
      getClaimDisabledReason({
        connected: false,
        hasPublicKey: false,
        soul: soul(),
      }),
    ).toBe("connectWallet");
  });

  it("requires an unclaimed generated SVG", () => {
    expect(
      getClaimDisabledReason({
        connected: true,
        hasPublicKey: true,
        soul: soul({ lastSvgLen: 0 }),
      }),
    ).toBe("generateFirst");

    expect(
      getClaimDisabledReason({
        connected: true,
        hasPublicKey: true,
        soul: soul({ generationCount: 2n, claimCount: 2n }),
      }),
    ).toBe("alreadyClaimed");
  });

  it("allows claim when wallet is connected and claim_count is behind generation_count", () => {
    expect(
      getClaimDisabledReason({
        connected: true,
        hasPublicKey: true,
        walletPublicKey: connectedWallet,
        soul: claimableSoul({ generationCount: 3n, claimCount: 1n }),
        walletTokenBalanceBaseUnits: MIN_CLAIM_BALANCE,
      }),
    ).toBeNull();
  });

  it("requires one 10,000-token MT quantum before enabling claim", () => {
    expect(
      getClaimDisabledReason({
        connected: true,
        hasPublicKey: true,
        walletPublicKey: connectedWallet,
        soul: claimableSoul({ generationCount: 3n, claimCount: 1n }),
        walletTokenBalanceBaseUnits: MIN_CLAIM_BALANCE - 1n,
      }),
    ).toBe("insufficientBalance");

    expect(
      getClaimDisabledReason({
        connected: true,
        hasPublicKey: true,
        walletPublicKey: connectedWallet,
        soul: claimableSoul({ generationCount: 3n, claimCount: 1n }),
        walletTokenBalanceBaseUnits: MIN_CLAIM_BALANCE,
      }),
    ).toBeNull();
  });

  it("blocks sub-whole, sell-generated, and legacy Souls before balance-only checks", () => {
    expect(
      getClaimDisabledReason({
        connected: true,
        hasPublicKey: true,
        walletPublicKey: connectedWallet,
        soul: soul({
          generationCount: 2n,
          claimCount: 1n,
          provenanceGeneration: 2n,
          provenanceSide: SOUL_PROVENANCE_SIDE.Buy,
          provenanceAmount: 5_000_000_000n,
          provenanceTokenAmount: MIN_CLAIM_BALANCE - 1n,
          provenanceTrader: connectedWallet,
        }),
        walletTokenBalanceBaseUnits: MIN_CLAIM_BALANCE,
      }),
    ).toBe("provenanceSubWhole");

    expect(
      getClaimDisabledReason({
        connected: true,
        hasPublicKey: true,
        walletPublicKey: connectedWallet,
        soul: soul({
          generationCount: 2n,
          claimCount: 1n,
          provenanceGeneration: 2n,
          provenanceSide: SOUL_PROVENANCE_SIDE.Sell,
          provenanceAmount: 10_000_000n,
          provenanceTokenAmount: 0n,
          provenanceTrader: connectedWallet,
        }),
        walletTokenBalanceBaseUnits: 10_000_000n,
      }),
    ).toBe("provenanceSellGenerated");

    expect(
      getClaimDisabledReason({
        connected: true,
        hasPublicKey: true,
        walletPublicKey: connectedWallet,
        soul: soul({ generationCount: 2n, claimCount: 1n }),
        walletTokenBalanceBaseUnits: 10_000_000n,
      }),
    ).toBe("provenanceMissing");
  });
});
